# A URL aponta para um arquivo local na raiz do projeto chamado "meubanco.db"
spring.datasource.url=jdbc:sqlite:sqlite3.db

# Define o driver do SQLite
spring.datasource.driver-class-name=org.sqlite.JDBC

# Diz ao Hibernate para traduzir o SQL para a "linguagem" do SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Mostra o SQL gerado no console (opcional, bom para debugar)
spring.jpa.show-sql=true

# Cria ou atualiza as tabelas automaticamente com base nas classes @Entity
spring.jpa.hibernate.ddl-auto=update